language: ruby
rvm: 1.9.3
before_script:
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rspec
- bundle exec cucumber
deploy:
  provider: heroku
  api_key:
    secure: xpyfONK9cpCxQp+sI3UuiSKOBRr2+A12CoWzTOgTnXHerFKxiNvL95ZeXRI1B8otT/MjV5AolGxp0/i5glsd+d4uGrYRw0wwJWnB/I+j0QhECDFVM5WKHI4TKnsroOWgf865DavL1InWC8ZWHUsrllGtddH2dyr3knMSefKSZuM=
  app:
    master: kleer
    develop: kleer-test
